### ISSUE TITLE
PC002 Registro de aspirantes a EC

### ISSUE THREAD

**Issue by SusanaRubioM** [SusanaRubioM/CONAFE#3]
Como aspirante a EC, quiero poder cargar mis datos en el sistema para ser considerado en el proceso de selección como educador  comunitario

Accediendo al link de registro publicado en la convocatoria de promoción y captación por el CT (PC003)
El sistema debe permitir la carga de datos:
Información básica
Nombre (obligatorio)
Apellidos (obligatorio)
Edad (obligatorio)
Sexo (obligatorio)
Correo electrónico (obligatorio)
Número de teléfono (obligatorio)
Formación académica (nivel de estudios, título obtenido, institución) (obligatorio)
CURP 	(obligatorio)
Fotografía (obligatorio)
	
Información de gestión
¿Hablas alguna lengua indígena? ¿Cuál? (opcional)
Talla de playera (obligatorio)
Talla de pantalón (obligatorio)
Talla Calzado (obligatorio)
Peso (obligatorio)
Estatura (obligatorio)
Banco (opcional)
Cuenta bancaria (opcional)

Residencia
Código postal (obligatorio)
Estado (obligatorio)
Municipio o Alcaldía (obligatorio)
Localidad (opcional)
Colonia (obligatorio)
Calle (obligatorio)
Participación	
Estado en el que deseas participar (obligatorio)
Ciclo escolar para participar (obligatorio)
Programa en el que deseas participar (EC) (obligatorio)
Tipo de servicio (Inicial, Preescolar, primaria, secundaria, postsecundaria) (obligatorio)
Contexto (indigena, mestizo, migrante, circense, grupos vulnerables, excluidos del sistema regular) (obligatorio)

Datos estadísticos
Medio por el cuál te enteraste (obligatorio)

El aspirante debe poder editar su información antes de enviarla.
Debe haber un botón de "Enviar" que confirme que la información ha sido recibida y está en proceso de revisión
El sistema debe validar que todos los campos obligatorios estén completos antes de permitir el envío
El aspirante debe recibir una confirmación de que sus datos han sido registrados exitosamente y recibirá notificación por correo electrónico despues de dar enviar.

**Comment by emmanuelcodedev** [comment]
completo
